In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import openktn as okn
from simtk.unit import kelvin, picoseconds

# Networkx Kinetic Transition Network

In [3]:
net = okn.kinetic_transition_network(form='pandas.KineticTransitionNetwork',
                                    temperature=300.0*kelvin, time_step=10*picoseconds)

In [4]:
okn.info(net)

In [5]:
okn.add_microstate(net)

In [6]:
okn.info(net, target='microstate')

In [7]:
okn.add_microstate(net, name='A')

In [8]:
okn.info(net, target='microstate')

In [9]:
okn.add_microstate(net, index=4)

In [10]:
okn.info(net, target='microstate')

In [11]:
okn.add_transition(net, origin='A', end=3, weight=1.0)

In [12]:
net.transitions

index origin_index end_index weight probability symmetrized
0     0            1         3      1           0       False

In [13]:
okn.info(net)

In [14]:
okn.info(net, target='microstate')

In [15]:
okn.info(net, target='transition')

In [16]:
okn.add_transition(net, origin=0, end=2, weight=4.0, origin_index=True, end_index=True)

In [17]:
okn.info(net, target='transition')

In [18]:
net.transitions

index origin_index end_index weight probability symmetrized
0     0            1         3      1           0       False
1     1            0         2      4           0       False

In [19]:
okn.info(net)

In [20]:
okn.info(net, target='microstate')

In [21]:
okn.update_probabilities(net)

In [22]:
okn.info(net, target='microstate')

In [23]:
okn.info(net, target='transition')

In [24]:
okn.symmetrize(net)

In [25]:
okn.info(net, target='microstate')

In [26]:
okn.info(net, target='transition')

In [1]:
import numpy as np

In [2]:
np.array([]).any()

False

In [3]:
from pandas import DataFrame

In [4]:
df = DataFrame(columns=['A','B'])

In [5]:
df

Empty DataFrame
Columns: [A, B]
Index: []

In [10]:
df.at[2,'B']='chas'

In [24]:
((df.A.to_numpy()=='hola') * (df.A.to_numpy()=='chas')).any()

False

In [25]:
df.A.to_numpy()=='hola'

array([ True, False])

In [26]:
(df.A=='hola').to_numpy()

array([ True, False])

In [32]:
df.loc[0].index

KeyError: 0

In [35]:
aa=df.A.to_numpy()

In [36]:
aa

array(['hola', 'holo'], dtype=object)

In [37]:
np.where(aa,'hola')

ValueError: either both or neither of x and y should be given

In [50]:
aa=np.array([3,6,8,2,1,0,9])

In [39]:
bb=[8,3,0]

In [40]:
np.argwhere(aa,ii)

In [59]:
np.where(aa==8)

(array([2]),)

In [64]:
np.asarray(aa==8).nonzero()[0][0]

2

In [54]:
np.argwhere(aa==8)[0]

array([2])

In [48]:
np.asarray((aa==8)).nonzero()

/home/diego/Myopt/miniconda3/envs/UIBCDF_lab_dev/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  """Entry point for launching an IPython kernel.


(array([], dtype=int64),)

In [49]:
aa==8

False

In [67]:
def buh(aa,bb):
    output=np.argwhere(aa==bb)[0][0]
    return output

In [68]:
buh(aa,8)

2

In [74]:
vf=np.vectorize(buh, excluded=[0])

In [75]:
vf(aa,bb)

array([2, 0, 5])